project:
  type: book
  output-dir: _book

book:
  title: "Mire trenching indicator"
  author: "Anders Kolstad"
  date: last-modified
  description: | 
    An investigating into different consepts for an ecosystem condition indicator based on a map of mire trenches i Norway.
  repo-url: https://github.com/NINAnor/mire-trenching
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - study-area.qmd
    - delineation.qmd
    - metrics.qmd
    - how-to-update.qmd
    - 7TK.qmd
    - referenceLevels.qmd

format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    
    code-link: true

bibliography: references.bib
csl: NINArefStyle.csl
